name: Test and build

on:
  push:
    branches:
      - master
      - registry

jobs:
  test_nostr-rs-relay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          sudo apt-get install -y protobuf-compiler
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      # - name: Lint
      #   run: |
      #     cargo fmt -- --check
      #     cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build --release --locked

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/registry'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image for registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/registry'
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/nostr-rs-relay:${{ github.sha }} .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/nostr-rs-relay:${{ github.sha }} ghcr.io/${{ secrets.GHCR_USERNAME }}/nostr-rs-relay:latest

      - name: Push Docker image to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/registry'
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/nostr-rs-relay:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/nostr-rs-relay:latest
